---
title: "R Notebook"
output: html_notebook
---

# 2. Hausaufgabe

```{r}
library(tidyverse)
```
 
## Beziehung zwischen Anzahl der Bücher/Publisher und deren Bewertungen
  
```{r}
ISBNPublisher <- BX_Books %>%
  select(ISBN, Publisher)
```
  
```{r}
AnzahlBooks <- BX_Books %>%
  select(Publisher, ISBN) %>%
  group_by(Publisher) %>%
  summarise(AnzahlDerBücher = n())
```

```{r}
gemeinsam <- merge(BX_Book_Ratings, BX_Books)
```

```{r}
AnzahlRatings <- merge(BX_Book_Ratings, BX_Books) %>%
  group_by(Publisher) %>%
  summarise(AnzahlDerRatings = n())
```

```{r}
Relation <- merge(AnzahlBooks, AnzahlRatings)# %>%
  #select(AnzahlDerBücher, AnzahlDerRatings)
```

```{r}
plot(Relation)
```


## Zeitalter der Bücher und der Einfluss auf deren Bewertung

```{r}
AlterBooks <- BX_Books %>%
  select(`Year-Of-Publication`, ISBN) %>%
  group_by(`Year-Of-Publication`) %>%
  summarise(AlterDerBücher = n())
  
```

```{r}
AlterBooks <- merge(BX_Books, BX_Book_Ratings) %>%
  group_by(`Year-Of-Publication`) %>%
  summarise(BucherInDemJahr = n()) %>%
  filter(`Year-Of-Publication` > 1500)
```

```{r}
plot(AlterBooks)
```

